### ISSUE TITLE
Data not found error displayed when selecting "Charts" tab for some datasets 

### ISSUE THREAD

**Issue by emmorris** [RhoInc/data-library#27]
This may be expected, but when I click some of the datasets in the “Files” tab and then select the “Charts” tab I get an error stating “Data not found.  Update filters to try again.”  The files that do that are:

On the sdtm –cdisc pilot 01 datasets page:

- meta_study

- sppdm

On the data dictionaries datasets page:

- fields

- forms

- medications

**Comment by samussiah** [comment]
web-codebook issue, logged [here](https://github.com/RhoInc/web-codebook/issues/314)
