### ISSUE TITLE
Change our dataset for the enrollment chart to include the new filter columns

### ISSUE THREAD

**Issue by emmorris** [RhoInc/data-library#30]
Change our dataset for the enrollment chart to include the new filter columns.  Spencer saved a new version of the dataset down on the network for Heather's reference, so we just need to find that and put it in the library.

**Comment by pburnsdata** [comment]
@samussiah where is this file emily mentioned? You don't need to answer this till you get back. Give your full attention to the lake and buzzards and wife!

![image](https://user-images.githubusercontent.com/26064686/61956719-b431fa80-af8b-11e9-8591-6105ba9e486c.png)

**Comment by emmorris** [comment]
@pburnsdata , I think I found it.  I believe it is the csv file here: I:\SHARE\COMMITTEES\DM Evolution\Renderers\Renderer Design Folder\Enrollment Renderer
