### ISSUE TITLE
Add a new accrual over time data file with a study-level accrual target instead of site-level accrual targets.

### ISSUE THREAD

**Issue by pburnsdata** [RhoInc/data-library#37]
from https://github.com/RhoInc/dashboard-charts/issues/19

Implemented this by adding Overall and Site Target Rows - but wasn't totally clear on requirements here

**Comment by samussiah** [comment]
For now site-level targets will suffice.  We'll want to revisit this one at some point and just create a new study-level accrual over time data file.

**Comment by samussiah** [comment]
I like the way you implemented this @pburnsdata .  Let's adapt `dashboard-enrollment.R` to generate the study-level target data file.
